steps:

- name: gcr.io/cloud-builders/npm:node-18.12.0
  args: [ install ]

- name: gcr.io/cloud-builders/npm:node-18.12.0
  args: [ run, build, --prod ]

- name: gcr.io/cloud-builders/gcloud
  args: [ app, deploy, --version=$SHORT_SHA ]

options:
  logging: CLOUD_LOGGING_ONLY