steps:
- name: 'node:20'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # Display Node.js and npm versions
    node -v
    npm -v
    # Clean and reinstall dependencies
    rm -rf node_modules package-lock.json
    npm install --legacy-peer-deps

- name: 'node:20'
  args: ['npm', 'run', 'build', '--prod']

- name: gcr.io/cloud-builders/gcloud
  args: ['app', 'deploy', '--version=$SHORT_SHA']

options:
  logging: CLOUD_LOGGING_ONLY
